table 'Product Categories Lookup'
	lineageTag: 87fe3f64-2bee-4c82-b1b8-5cf5e92db3a8

	column ProductCategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 4eb97da6-b836-4c3e-b980-2b29b0b1ae2d
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: a18f4dc3-2be1-4a89-897c-b92681a6ac32
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				    Источник = Csv.Document(File.Contents("C:\Users\user\Downloads\Power BI\AdventureWorks Raw Data\AdventureWorks Raw Data\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Повышенные заголовки" = Table.PromoteHeaders(Источник, [PromoteAllScalars=true]),
				    #"Измененный тип" = Table.TransformColumnTypes(#"Повышенные заголовки",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Измененный тип"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

