table 'Product Subcategories Lookup'
	lineageTag: 93a1e204-e5f5-4fca-b937-fa26748e3da9

	column ProductSubcategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: a48ea33b-d720-435e-ac65-2ff3fd001a8c
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 906892a8-9a0d-4b31-8715-3994b8ed30da
		summarizeBy: none
		sourceColumn: SubcategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: cd8337b8-0ee0-4095-8a09-795508f54fc9
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Источник = Csv.Document(File.Contents("C:\Users\user\Downloads\Power BI\AdventureWorks Raw Data\AdventureWorks Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Повышенные заголовки" = Table.PromoteHeaders(Источник, [PromoteAllScalars=true]),
				    #"Измененный тип" = Table.TransformColumnTypes(#"Повышенные заголовки",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Измененный тип"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

